import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { NeonAuthUIProvider, UserButton } from "@neondatabase/auth/react";
import { authClient } from "@/lib/auth/client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[var(--background)] text-[var(--foreground)] text-[var(--font-size)]">
        <NeonAuthUIProvider authClient={authClient as any}>
          <header className=" border-b border-[var(--border)] bg-[var(--foreground)]/90 backdrop-blur ">
            <div className=" mx-auto flex items-center justify-between h-16 w-full max-w-6xl px-4">
              <Link
                href="/"
                className=" text-sm font-extrabold tracking-widess"
              >
                Event Planner
              </Link>
              <nav className="flex items-center gap-4">
                <Link
                  href="/dashboard"
                  className=" text-sm text-[var(--muted--foreground)}"
                >
                  Dashboard
                </Link>
                <UserButton size="icon" />
              </nav>
            </div>
          </header>
          <main className="flex mx-auto w-full max-w-6xl flex-col flex-1 px-4 py-8">
            {children}
          </main>
        </NeonAuthUIProvider>
      </body>
    </html>
  );
}
